---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infrastructure
spec:
  interval: 1m
  url: https://github.com/dginther/kargo
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: instance_1
spec:
  path: ./terraform
  approvePlan: "auto"
  destroyResourcesOnDeletion: true
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: infrastructure
  varsFrom:
    - kind: Secret
      name: aws-credentials

