apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/dginther/kargo
    targetRevision: main
    path: ./infra
  syncPolicy:
    syncOptions:
      - FluxSubsystem=true
      - AutoCreateFluxResources=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true