apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: cert-manager
spec:
  project: default
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io
    syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    chart: cert-manager
    targetRevision: v1.13.1
    helm:
      skipCrds: false
      parameters:
        - name: "installCRDs"
          value: "true"
          forceString: true
  
