apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: kargo
spec:
  project: default
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: kargo
  source:
    repoURL: "https://ghcr.io/akuity/kargo-charts/kargo"
    chart: kargo
    targetRevision: v1.13.1
    helm:
      skipCrds: false
      parameters:
        - name: "api.adminAccount.password"
          value: "temporaryPassword"
          forceString: true
        - name: "api.adminAccount.tokenSigningKey"
          value: "ThisIsATokenSigningKey"
          forceString: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
