apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:staging
spec:
  project: default
  source:
    repoURL: https://github.com/dginther/kargo-demo
    targetRevision: stage/staging
    path: stages/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging