apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:dev
spec:
  project: default
  source:
    repoURL: ${GITOPS_REPO_URL}
    targetRevision: stage/dev
    path: stages/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev