apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tf-controller
  namespace: flux-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: flux-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://weaveworks.github.io/tf-controller
    chart: tf-controller
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - FluxSubsystem=true
      - AutoCreateFluxResources=true
      - ApplyOutOfSyncOnly=true
